modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="islands"
version="1.0.0"
displayName="Islands"
displayURL="https://www.pixelatedw.xyz/"
logoFile="examplemod.png"
authors="Wynd"
description='''
Simple mod that adds a new World Type for generating and endless ocean filled with islands.

Dev Team :
    Wynd - Progammer 
'''

[[dependencies.islands]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.islands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
